{
 "title": "Traefik  Realtime Stats",
 "description": "Visualize Traefik Health Metrics",
 "tags": [
  "traefik",
  "load-balancer"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Total requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "sum(traefik_entrypoint_requests_total) by (protocol)",
     "legendFormat": "{{ protocol }}"
    }
   ]
  },
  {
   "title": "Average response time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(traefik_backend_request_duration_seconds_sum) / sum(traefik_backend_requests_total) * 1000",
     "legendFormat": "Average response time (ms)"
    }
   ]
  },
  {
   "title": "Requests in last 5 minutes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(traefik_backend_requests_total[5m]))",
     "legendFormat": "{{requests}}"
    }
   ]
  },
  {
   "title": "Successful Status Code Count (5min)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(traefik_backend_requests_total{protocol=~\"http|https\",code=\"200\"}[5m])) by (backend,method)",
     "legendFormat": "{{service}} {{method}}"
    }
   ]
  },
  {
   "title": "Bad Status Code Count (5m)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(traefik_backend_requests_total{protocol=~\"http|https\",code!=\"200\"}[5m])) by (backend,method,code)",
     "legendFormat": "{{backend}} {{method}} {{code}}"
    }
   ]
  },
  {
   "title": "Used sockets",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_open_fds{job=~\"load-balancer\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  }
 ]
}