image: docker:latest

stages:
  # - build
  - deploy-to-swarm

# build:
#     stage: build
#     script:
#         - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
#         - docker pull $CONTAINER_IMAGE:latest || true
#         - docker build --cache-from $CONTAINER_IMAGE:latest --tag $CONTAINER_IMAGE:$CI_BUILD_REF --tag $CONTAINER_IMAGE:latest ./
#         - docker push $CONTAINER_IMAGE:$CI_BUILD_REF
#         - docker push $CONTAINER_IMAGE:latest
#     only:
#         - master

deploy-to-swarm:
  stage: deploy-to-swarm
  variables:
    DOCKER_HOST: tcp://$HOST:2376
    DOCKER_TLS_VERIFY: 1
    DOCKER_CERT_PATH: "/certs"
  script:
    - mkdir -p $DOCKER_CERT_PATH
    - echo "$TLSCACERT" > $DOCKER_CERT_PATH/ca.pem
    - echo "$TLSCERT" > $DOCKER_CERT_PATH/cert.pem
    - echo "$TLSKEY" > $DOCKER_CERT_PATH/key.pem
    - docker login -u root -p $HUB_REGISTRY_PASSWORD $CI_REGISTRY
    - cd stacks/traefik
    - docker stack deploy -c metrics.ymll $SERVICE_NAME --with-regist
  only:
    - master