version: '3'

services:
  reverse-proxy:
    image: traefik
    command: --api --docker --docker.domain=${HOST:-localhost} --docker.network=${SERVICE_NAME:-default}_default --docker.watch
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock